server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/toolmates_db
spring.datasource.username=root
spring.datasource.password=20540

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your-app@gmail.com
spring.mail.password=YOUR_APP_PASSWORD
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.cors.allowed-origins=http://localhost:3000
server.servlet.session.timeout=15m